language: node_js
node_js:
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
after_success:
  - npm run-script coveralls
notifications:
  email: false
